<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\Artisan;
use Tests\Traits\DatabaseTestHelper;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    use DatabaseTestHelper;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Artisan::call('migrate', [
            '--path' => '/database/migrations/LaraMessengerTables'
        ]);

        Artisan::call('migrate', [
            '--path' => '/database/migrations/LaraMessengerForeignKeys'
        ]);

        $this->createTestData();
    }
}
